stages:
  - test
  - build
  - confirm
  - deploy

variables:
  CI_REGISTRY: docker.shlab.tech
  CI_REGISTRY_USER: cicd@1397355716557288
  CI_REGISTRY_PASSWORD: QUE5MTAwQzEtQkEyMi00Q0QxLTg0MDYt

before_script:
  - export IMAGE_REPOSITORY=${CI_PROJECT_PATH}
  - export IMAGE_TAG=${CI_COMMIT_BRANCH}.${CI_PIPELINE_IID:-c.${CI_COMMIT_SHA:0:8}}
  - export IMAGE_NAME=${CI_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_TAG}

test:
  stage: test
  image:
    name: docker.shlab.tech/public/node:22-alpine
    entrypoint: [""]
  script:
    - npm ci --registry=https://npm.shlab.tech
    - npm run check

build:
  stage: build
  rules:
    - if: "$CI_COMMIT_REF_NAME =~ /^(main|dev)$/"
  image:
    name: docker.shlab.tech/public/kaniko-executor:debug
    entrypoint: [""]
  cache:
    paths:
      - /cache
  retry: 2
  script:
    - export
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${IMAGE_NAME}"
      --cache=true
      --force

confirm_production_deployment:
  stage: confirm
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'main'"
      when: manual
  script:
    - echo "确认部署到生产环境"

deploy:
  stage: deploy
  image: node:20-alpine
  needs:
    - job: build
    - job: confirm_production_deployment
      optional: true
  variables:
    GITOPS_TOKEN: ${GITOPS_TOKEN}
  rules:
    - if: "$CI_COMMIT_REF_NAME == 'main'"
      when: on_success
    - if: "$CI_COMMIT_REF_NAME == 'dev'"
      when: on_success
  script:
    - echo $IMAGE_NAME
    - export GIT_TAG="${CI_PROJECT_NAME}@v${IMAGE_TAG}"
    - if [ "$CI_COMMIT_REF_NAME" = "main" ]; then export APP_ENV=prod; else export APP_ENV=dev; fi
    - DEBUG=* npm_config_registry="https://npm.shlab.tech" npx gitops-deploy -c ./deployrc.${APP_ENV}.json
