stages:
  - dry-run
  - build
  - deploy

before_script:
  - export IMAGE_TAG=${CI_COMMIT_TAG:-${CI_COMMIT_BRANCH}.${CI_PIPELINE_IID:-c.${CI_COMMIT_SHA:0:8}}}
  - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then export APP_ENV="prod"; elif [ "$CI_COMMIT_REF_NAME" == "dev" ]; then export APP_ENV="dev"; fi

pre-develop:
  stage: dry-run
  only:
    - dev
  image: gitlab.pjlab.org.cn:5050/dps-registry/hub/node:22-alpine
  script:
    - echo "next-version=$CI_COMMIT_BRANCH.$CI_PIPELINE_IID" >> version.txt
  artifacts:
    paths:
      - version.txt

release-dry-run:
  stage: dry-run
  image: gitlab.pjlab.org.cn:5050/dps-registry/hub/node:22-alpine
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - OUTPUT="$(bash -c "npx --registry=https://npm.shlab.tech --yes -p semantic-release@24.2.8 -p @semantic-release/gitlab -p @shlab/commit-analyzer -p @semantic-release/release-notes-generator@14 -p @semantic-release/git@10 -p conventional-changelog-conventionalcommits@8 semantic-release --dry-run 2>&1 | tee /dev/stderr")"
    - NEW_RELEASE_VERSION=$(echo "$OUTPUT" | grep -ioP 'The next release version is \K(\d+\.\d+\.\d+(-\w*(-\w*)*\.\d+)?)')
    - echo "$NEW_RELEASE_VERSION"
    - echo "next-version=$NEW_RELEASE_VERSION" >> version.txt
  artifacts:
    paths:
      - version.txt

build-image:
  stage: build
  rules:
    - if: "$CI_COMMIT_REF_NAME =~ /^(main|dev)$/"
  dependencies:
    - release-dry-run
    - pre-develop
  image:
    name: docker.shlab.tech/public/kaniko-executor:debug
    entrypoint: [""]
  cache:
    paths:
      - /cache
  retry: 2
  script:
    - export IMAGE_TAG=$(grep next-version version.txt | cut -d'=' -f2)
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${GL_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - export IMAGE_NAME=${CI_REGISTRY}/${PUBLIC_REGISTRY_NAMESPACE}/${CI_PROJECT_NAME}:${IMAGE_TAG}
    - echo $IMAGE_NAME
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${IMAGE_NAME}"
      --cache=true
      --force

deploy-dev:
  stage: deploy
  image: node:20-alpine
  needs:
    - pre-develop
    - build-image
  dependencies:
    - pre-develop
    - build-image
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
  environment:
    name: dev
  variables:
    APP_ENV: dev
  script:
    - export IMAGE_TAG=$(grep next-version version.txt | cut -d'=' -f2)
    - echo $IMAGE_TAG
    - export GIT_TAG="/${CI_PROJECT_NAME}@v${IMAGE_TAG}"
    - DEBUG=* npm_config_registry=https://npm.shlab.tech npx gitops-deploy -c ./deployrc.${APP_ENV}.json

deploy-prod:
  stage: deploy
  image: node:20-alpine
  needs:
    - release-dry-run
    - build-image
  dependencies:
    - release-dry-run
    - build-image
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  environment:
    name: prod
  variables:
    APP_ENV: prod
  script:
    - export IMAGE_TAG=$(grep next-version version.txt | cut -d'=' -f2)
    - echo $IMAGE_TAG
    - export GIT_TAG="/${CI_PROJECT_NAME}@v${IMAGE_TAG}"
    - DEBUG=* npm_config_registry=https://npm.shlab.tech npx gitops-deploy -c ./deployrc.${APP_ENV}.json

release:
  stage: .post
  image: gitlab.pjlab.org.cn:5050/dps-registry/hub/node:22-alpine
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  dependencies:
    - release-dry-run
  script:
    - export NEXT_VERSION=$(grep next-version version.txt | cut -d'=' -f2)
    - sed -i "s/\"version\":\ \".*\"/\"version\":\ \"${NEXT_VERSION}\"/" ./package.json
    - npx --registry=https://npm.shlab.tech --yes -p semantic-release@24.2.8 -p @semantic-release/gitlab -p @shlab/commit-analyzer -p @semantic-release/release-notes-generator -p @semantic-release/git -p conventional-changelog-conventionalcommits semantic-release

dev-notification:
  stage: .pre
  image: curlimages/curl
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      when: on_success
  script:
    - >-
      echo "{\"msg_type\":\"interactive\",\"card\":{\"elements\":[{\"tag\":\"div\",\"text\":{\"tag\":\"lark_md\",\"content\":\"${CI_PROJECT_NAME} ${CI_COMMIT_MESSAGE} 👉🏻 [${CI_COMMIT_SHORT_SHA}](https://pjlab.gitlab.org.cn/${CI_PROJECT_PATH}/-/commit/${CI_COMMIT_SHA})\"}}]}}" | \
        curl -X POST -H 'Content-Type: application/json; charset=utf-8' -d @- ${BOT_WEBHOOK}
